name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ...existing code...

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Run golangci-lint
        run: cd go-launcher && golangci-lint run --timeout=5m

  go-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Go coverage
        run: cd go-launcher && go test -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: go-launcher/coverage.out
          flags: go
          token: ${{ secrets.CODECOV_TOKEN }}

  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run cargo clippy
        run: cd rust-launcher && cargo clippy --all -- -D warnings

  rust-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run Rust coverage
        run: cd rust-launcher && cargo tarpaulin --out Xml --output-dir .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: rust-launcher/cobertura.xml
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}
